version: 2.1
orbs:
  # Use the CircleCI Android orb version that supports OpenJDK17 required by AGP 8.2+
  android: circleci/android@2.1.2
  codecov: codecov/codecov@3.2.4

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 3
  build-test-deploy:
    jobs:
      - validate-code:
          gradle-cache-prefix: v1
          build-cache-prefix: v1

      - build-and-unit-test:
          gradle-cache-prefix: v1
          build-cache-prefix: v1
          requires:
            - validate-code
      
      - functional-test:
          gradle-cache-prefix: v1
          build-cache-prefix: v1
          requires:
            - validate-code
 
jobs:
  validate-code:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1
  
    # List of available Android Docker images: https://circleci.com/developer/images/image/cimg/android#image-tags
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2022.09.2-node

    steps:
      - checkout

      - android/restore-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/restore-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      - run:
          name: Check Code Format
          command: make format-check

      - android/save-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/save-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>  

  build-and-unit-test:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1

    # List of available Android Docker images: https://circleci.com/developer/images/image/cimg/android#image-tags
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2022.09.2-node

    steps:
      - checkout

      - android/restore-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/restore-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      - run:
          name: Javadoc
          command: make ci-javadoc
      - store_artifacts:
          path: ci/javadoc/build/reports

      - run:
          name: Build
          command: make ci-build

      - run:
          name: Build App
          command: make ci-build-app

      - run:
          name: UnitTests
          command: make ci-unit-test

            # code coverage
      - run:
          name: Upload Code Coverage Report
          command: |
            curl -s https://codecov.io/bash > codecov;
            VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
            SHAVERSION=$(shasum -v);
            echo "Using CodeCov version '$VERSION'"
            echo "Using shasum '$SHAVERSION'"
            for i in 1 256 512
            do
              shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") ||
              shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep -w "codecov")
            done
            bash ./codecov -v -X s3 -c -D "./ci/unit-test/build/reports" -F unit-tests

      - store_artifacts:
          path: ci/unit-test/build/reports

      - store_test_results:
          path: ci/unit-test/build/test-results
      
      - android/save-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/save-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

  functional-test:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1

    executor: 
      name: android/android-docker
      resource-class: large
      tag: 2022.09.2-node

    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          #   It should match the name seen in the "sdkmanager --list" output
          system-image: system-images;android-29;default;x86
          #   The command to be run, while waiting for emulator startup
          post-emulator-launch-assemble-command: make ci-build
          #   The test command
          test-command: make ci-functional-test

      # code coverage
      - run:
          name: Upload Code Coverage Report
          command: |
            curl -s https://codecov.io/bash > codecov;
            VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
            SHAVERSION=$(shasum -v);
            echo "Using CodeCov version '$VERSION'"
            echo "Using shasum '$SHAVERSION'"
            for i in 1 256 512
            do
              shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") ||
              shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep -w "codecov")
            done
            bash ./codecov -v -X s3 -c -D "./ci/functional-test/build/reports" -F functional-tests

      - store_artifacts:
          path: ci/functional-test/build/reports

      - store_test_results:
          path: ci/functional-test/build/outputs/androidTest-results

