version: 2.1
orbs:
  # Use the CircleCI Android orb version that supports OpenJDK17 required by AGP 8.2+
  android: circleci/android@2.4.0
  codecov: codecov/codecov@3.2.4

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 3
  build-test-deploy:
    jobs:
      - validate-code:
          gradle-cache-prefix: v1
          build-cache-prefix: v1

      - build-and-unit-test:
          gradle-cache-prefix: v1
          build-cache-prefix: v1
          requires:
            - validate-code

jobs:
  validate-code:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1

    # List of available Android Docker images: https://circleci.com/developer/images/image/cimg/android#image-tags
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2024.01.1

    steps:
      - checkout

      - android/restore-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/restore-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      - run:
          name: Check Code Format
          command: make format-check

      - run:
          name: Lint Code
          command: make lint

      - android/save-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/save-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>      

      # Store Lint report
      - store_artifacts:
          path: code/edgeconsent/build/reports

  build-and-unit-test:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1

    # List of available Android Docker images: https://circleci.com/developer/images/image/cimg/android#image-tags
    executor:
      name: android/android-docker
      resource-class: large
      tag: 2024.01.1
 
    steps:
      - checkout

      - android/restore-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/restore-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      - run:
          name: Build Library
          command: make build-library

      - run:
          name: Build Jitpack Library
          command: make ci-publish-maven-local-jitpack
